import os

CHAPTER_ORDER = [
    "prologue",
    "chapter-1",
    "chapter-2",
    "chapter-3",
    "chapter-4",
    "chapter-5",
    "chapter-6",
    "chapter-7",
    "chapter-8",
    "chapter-9",
    "chapter-10",
    "chapter-11",
    "chapter-12",
    "chapter-13",
    "chapter-14",
    "chapter-15",
    "chapter-16",
    "chapter-17",
    "chapter-18",
    "chapter-19",
    "chapter-20",
    "chapter-21",
    "chapter-22",
]

COVER_IMAGE = "learning_to_see.png"

cover_html = ""
if os.path.exists(COVER_IMAGE):
    cover_html = (
        '<div style="margin:0;padding:0;page-break-after:always;">'
        f'<img src="{COVER_IMAGE}" style="width:100%;height:100vh;object-fit:cover;display:block;">'
        '</div>'
    )
    print(f"  added cover: {COVER_IMAGE}")
else:
    print(f"WARNING: cover image {COVER_IMAGE} not found, skipping")

parts = [cover_html] if cover_html else []

for key in CHAPTER_ORDER:
    fname = f"{key}.md"
    if not os.path.exists(fname):
        print(f"WARNING: {fname} not found, skipping")
        continue
    with open(fname, "r", encoding="utf-8") as f:
        content = f.read().strip()
    parts.append(content)
    print(f"  read {fname}")

# Appendix: chronological notes (generated by process_all_notes.py)
NOTES_FILE = "processed_notes.md"
if os.path.exists(NOTES_FILE):
    with open(NOTES_FILE, "r", encoding="utf-8") as f:
        appendix = "# Appendix — Notes\n\n" + f.read().strip()
    parts.append(appendix)
    print(f"  appended {NOTES_FILE}")
else:
    print(f"WARNING: {NOTES_FILE} not found — run process_all_notes.py first")

with open("Book.md", "w", encoding="utf-8") as f:
    f.write("\n\n".join(parts) + "\n")

print(f"\nWrote Book.md ({len(parts)} section(s))")
